artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: amitabhajoy/bengaluru-house-price-data
  local_data_file: artifacts/data_ingestion/Bengaluru_House_Data.csv

data_validation:
  root_dir: artifacts/data_validation
  status_file: statusfile.json